### ISSUE TITLE
Might want to mention that `REGISTRY_STORAGE_DELETE_ENABLED` needs to be `true`

### ISSUE THREAD

**Issue by ryanmjacobs** [byrnedo/docker-reg-tool#16]
I wasn't able to delete until I started my private repo with this flag:
```bash
  -e REGISTRY_STORAGE_DELETE_ENABLED="true"
```
Maybe this could be noted in the readme?

**Comment by byrnedo** [comment]
Wanna make a pull request @ryanmjacobs ? :)

**Comment by ventz** [comment]
See my reply for the config option too:

https://github.com/byrnedo/docker-reg-tool/issues/19#issuecomment-1090472327

**Comment by byrnedo** [comment]
Thanks, updated the readme now.
