### ISSUE TITLE
Failed to delete: 405

### ISSUE THREAD

**Issue by dsoria** [byrnedo/docker-reg-tool#19]
Hi!
Hoping this script can help me delete some tags.

I tried delete and the error is:

DIGEST: sha256:b32067df1e504742bdea7c169916ddc51b848856f0d02c7b1c6a99c6533e5921
Failed to delete: 405

Regards

**Comment by jasondalysb** [comment]
Same result

**Comment by samjking** [comment]
I was getting the same result until I started the registry with  -e REGISTRY_STORAGE_DELETE_ENABLED="true"

After that, all was fine

**Comment by ventz** [comment]
@samjking Thanks for posting that! 
For anyone else, there is also config file option (which by default is turned off):

```
storage:
  delete:
    enabled: true
```

When you issue a delete, if you do not get a `Successfully deleted` message, make sure to list out the repos for `tags`:

Example
```
./docker_reg_tool https://registry.fqdn.tld list
repo1/image1
repo2/image2
...

# And you issue a delete:
./docker_reg_tool https://registry.fqdn.tld delete repo1/image1

# If you don't get "Successfully deleted", list out the tags#
./docker_reg_tool https://registry.fqdn.tld list repo1/image1
dev

# As an example, let's say you have only one and it's called "dev" in this case
# Then delete the tag(s):
./docker_reg_tool https://registry.fqdn.tld delete repo1/image1 dev
Successfully deleted

# At this point you will still see the repo due to garbage collection not kicking in:
./docker_reg_tool https://registry.fqdn.tld list
repo1/image1
repo2/image2
```

**Comment by byrnedo** [comment]
Updated the readme.
