### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by Bence98007** [byrnedo/docker-reg-tool#20]
Hi there!

Wanted to use your script, but when I issue this command:
`root@test:~ ./docker_reg_tool http://localhost:5000 list`
I get this error msg:
`./docker_reg_tool: line 73: jq: command not found`

Tried to add +x to the second line of the file, didnt help.
Any idea? 
Thanks! :)

**Comment by byrnedo** [comment]
Hi! You need to install jq on your distro.
