### ISSUE TITLE
Delete successfully but total size of registry data still equal before delete

### ISSUE THREAD

**Issue by pvanhungit** [byrnedo/docker-reg-tool#21]
Hi All, 
I deleted sucessfully, but total size in folder registry data still the same as before i deleted. So when we delete repo with tag, it will delete data or not ?

**Comment by pvanhungit** [comment]
Updated: It works fine for me when run garbage collector in docker registry image 
`docker exec registry bin/registry garbage-collect -m=true /etc/docker/registry/config.yml`

**Comment by byrnedo** [comment]
Yeah, sorry, I should add that to the readme.
