### ISSUE TITLE
~/.docker/config.json cannot have the protocol specified

### ISSUE THREAD

**Issue by jcross-linkup** [byrnedo/docker-reg-tool#8]
In my ~/.docker/config.json file I have the protocol specified.  That causes the following error:
```
$ ./docker_reg_tool https://docker-reg:5000 list repo
jq: error (at <stdin>:1): Cannot iterate over null (null)
```
I've created a pull request (#7) to allow the protocol to be specified in the ~/.docker/config.json file as well as ensure that jq doesn't return null silently when trying to extract the creds.

**Comment by byrnedo** [comment]
Thanks @jcross-linkup , have merged!
