### ISSUE TITLE
conditional binary operator expected

### ISSUE THREAD

**Issue by vladkras** [byrnedo/docker-reg-tool#9]
I catch this error `conditional binary operator expected` on every line with

```
if [[ -v "VARNAME" ]] ...
```
consider using

```
if [[ ${VARNAME} ]] ...
```
instead. It seems `-v` was introduced in bash 4+ while macos still uses version 3

**Comment by byrnedo** [comment]
ok, will fix

**Comment by vladkras** [comment]
@byrnedo, I replaced `-v` with `${...}` and checked on bash v.3 to 5 (see https://github.com/byrnedo/docker-reg-tool/pull/12)

Also I added Travis CI testing but I can exclude them from pull request https://github.com/byrnedo/docker-reg-tool/pull/12 if you don't need'em at all
